### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by iamakhileshmishra** [iamakhileshmishra/Mini_Projects_JavaScript#1]

**Comment by najeebkp** [comment]
Hi @iamakhileshmishra please assign me this task

**Comment by astitva0011** [comment]
hello, i would like to work on this issue. 
could you assign this issue to me?

**Comment by Radiosnack** [comment]
Hey ! I can add good description in readme section . 
You can assign this issue to me :)

**Comment by dynamicankur** [comment]
I would like to add meaningful Readme to this Repo please assign this to me

**Comment by Angshuman-Pal** [comment]
Hii @iamakhileshmishra 
Could you assign this to me I would like to work on it?
