### ISSUE TITLE
A good looking animated dropdown menu

### ISSUE THREAD

**Issue by Nataneljpwd** [iamakhileshmishra/Mini_Projects_JavaScript#12]
creating a good looking dark themes dropdown menu with css and js.

**Comment by iamakhileshmishra** [comment]
Go Ahead 👍

**Comment by siddhesh-coder** [comment]
plz assign me this issue

**Comment by Nataneljpwd** [comment]
hello I added the pr, please look at it.

**Comment by iamakhileshmishra** [comment]
@Nataneljpwd great job it's accepted now 🙌. Don't forgot to give a star to this repo.
